final links = [
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/Cooperating-with-the-Great-Work-Adolfo-Suero-Lecture-from-Usa-KoradiRadio-April-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Justin%20Short/Esoteric-Cliff-s-Notes-on-the-Aeneid-Justin-Short-Lecture-from-Usa-KoradiRadio-Aug-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/The-Awakening-of-Consciousness-part-1-Rafael-Arape-Lecture-from-Au-KR-Nov-2010.zip',
  'http://www.koradiaudio.com/radio_recordings/Davin%20Thomas/The-Psychology-of-the-Tarot-Part1-Davin-Thomas-Lecture-from-Usa-KR-Nov-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2015-with-Mr-Oscar-Uzcategui-VM-Kwen%20Khan-from-Brazil-KR-Jul-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Historic-and-Intimate-Christ-Rafael-Vargas-Holiday-Special-KoradiRadio-Dec-2011.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/Gnostic-Kabbala-and-the-Misuse-of-Speech-Part3-David-Serfati-Lecture-Mx-KR-Feb-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Patrick%20Donovan/Supernatural-Energy-in-the-Gnostic-Magic-of-the-Runes-Patrick-Donovan-Usa-KR-Jan-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/The-Awakening-Process-part3-Rafael-Arape-from-Australia-KoradiRadio-Nov-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part3-Taurus-Andrus-Shilling-Lecture-from-Usa-KR-Jul-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Poorang%20Aurasteh/The-Christic-Force-as-Sacrifice-Poorang-Aurasteh-Lecture-from-Usa-KR-Nov-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Javier Casañ/The-Power-of-Forgiveness-Javier-Casan-Lecture-from-Spain-KoradiRadio-Jul-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part10-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Sep-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Justin%20Short/Gnostic-Theology-Justin-Short-Lecture-from-Usa-KoradiRadio-Jan-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Davin%20Thomas/For-the-Love-of-the-Christ-Davin-Thomas-Lecture-from-Usa-KoradiRadio-May-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2014-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-English-Translation-RM-Dec-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Claudio Muñoz/Schools-of-Knowlegde-and-Schools-of-Wisdom-Claudio-Munoz-Lecture-C-Rica-KR-Oct-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part3-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Mar-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/VM-SAW-In-the-Present-and-the-Future-Jennifer-Hubicki-Lecture-from-Au-KR-Dec-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part9-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Aug-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part7-Virgo-Andrus-Shilling-Lecture-from-Usa-KR-Sep-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part19-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jun-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/Love-Lust-and-the-Ninth-Sphere-Paul-Movsessian-Lecture-from-Australia-KR-Jun-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/723-Extraterrestrials-Real-or-Not-David-Serfati-Lecture-from-France-KoradiRadio-Nov-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/In-the-Beginning-was-the-Word-Rene-Barge-Lecture-from-Brazil-KoradiRadio-Oct-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Jesús Gonzalez/The-Sin-Against-the-HS-and-Secret-Key-to-Avoid-SE-J-Gonzalez-Lecture-Mx-KR-May-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/The-Mystery-Religions-of-the-Ancients-part5-Andrus-Shilling-Lecture-Usa-KR-Oct-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Benjamin%20Matheson/The-Sickness-of-Tomorrow-Benjamin-Matheson-Lecture-from-Usa-KoradiRadio-Oct-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/850-Attacks-of-B-M-Prevention-and-Psychic-Defense-P3-D-Serfati-&-A-Shilling-KR-May-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/From-Darkness-into-the-Light-Robert-Marino-Lecture-from-Usa-KoradiRadio-Aug-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/871-Attacks-of-B-M-Prevention-and-Psychic-Defense-P4-David-Serfati-Mx-KR-Sep-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/Beethoven-Gnostic-at-Heart-Rene-Barge-Lecture-from-Brazil-KoradiRadio-Oct-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/Threshold-of-Awareness-Robert-Marino-Lecture-from-Usa-KoradiRadio-Apr-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/The-Unity-of-Force-Rene-Barge-Lecture-from-Brazil-KoradiRadio-January-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/Womans-Saintly-Predestination-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Apr-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Dorismel Díaz/830-Reconnecting-with-your-Innermost-Dorismel-Diaz-Practice-from-Canada-KR-Mar-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/Facing-our-Ancient-Past-through-the-9-Labours-of-Hercules-Jennifer-Hubicki-Au-KR-Aug-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/The-Great-Initiate-Women-Guillermina-Sanchez-Lecture-from-Sweden-KR-Jan-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/780-Attacks-of-B-M-Prevention-and-Psychic-Defense-P1B-David-Serfati-Mx-KR-Aug-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/671-Gnostic-Tarot-&-Kabalah-part5-Arcanum-3-Andrus-Shilling-Lecture-Usa-KR-Oct-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part8-Libra-Andrus-Shilling-Lecture-from-Usa-KR-Nov-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part17-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Apr-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/Freeing-the-Consciousness-from-its-Conditioning-Factors-part1-R-Arape-Au-KR-Feb-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/Interview-2014-with-Mr-Rafael-Vargas-from-Italy-KoradiRadio-Sep-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-New-Aquarian-Age-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Feb-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/788-Gnostic-Parenthood-P-1-Children-of-Wisdom-Ana-del-Angel-Lecture-Usa-KR-Sep-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/Contrasting-Virtues-and-Defects-Jennifer-Hubicki-Lecture-from-Australia-KR-Aug-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part5-Cancer-Andrus-Shilling-Lecture-from-Usa-KR-Aug-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/698-Gnostic-Tarot-&-Kabalah-part8-Arcanum-6-Andrus-Shilling-Lecture-Usa-KR-May-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/818-Crime-Part-1-Paul-Movsessian-Lecture-from-Australia-KoradiRadio-Jan-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part13-Andrus-Shilling-Lecture-from-Usa-KR-Oct-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Dorismel Díaz/El-Dorado-the-Mysteries-of-the-Leyend-Dorismel-Diaz-Lecture-from-Usa-KR-Mar-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Azzam/Universal-Mind-Diana-Azzam-Lecture-from-Australia-KoradiRadio-Feb-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/Pistis-Sophia-the-First-and-the-Last-Rene-Barge-Lecture-from-Brazil-KR-May-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part14-Conclusion-Andrus-Shilling-Lecture-from-Usa-KR-Mar-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/704-Gnostic-Tarot-&-Kabalah-part9-Arcanum-7-Andrus-Shilling-Lecture-Usa-KR-Jun-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Javier Casañ/The-Golden-Age-Javier-Casan-Lecture-from-Spain-KoradiRadio-Jan-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/The-Mystery-Religions-of-the-Ancients-part2-Andrus-Shilling-Lecture-Usa-KR-Jul-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Scott%20Billings/Mo-Chao-The-Revolution-of-Meditation-Scott-Billings-Lecture-from-UK-KR-Jun-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Encarnation-of-Christ-Today-Rafael-Vargas-Easter-Special-KoradiRadio-Apr-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/725-Gnostic-Tarot-&-Kabalah-part12-Arcanum-10-Andrus-Shilling-Lecture-Usa-KR-Nov-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/The-Iniciatic-Philosophy-Paul-Movsessian-Lecture-from-Australia-KoradiRadio-Jun-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part4-Gemini-Andrus-Shilling-Lecture-from-Usa-KR-Jul-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Javier Casañ/Faith-and-Conciousness-Javier-Casan-Lecture-from-Spain-KoradiRadio-Mar-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/The-Paramitas-the-Perfecting-of-the-Adept-Rene-Barge-Lecture-from-Brazil-KR-Oct-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Patrick%20Donovan/Choosing-your-Life-The-Dilemma-of-Duality-Patrick-Donovan-Lecture-Usa-KR-Sep-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part6-Andrus-Shilling-Lecture-from-Usa-KR-Feb-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Carlos%20Guevara/Gnosis-and-Aging-Carlos-Guevara-Lecture-from-Usa-KoradiRadio-Apr-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part9-Scorpio-Andrus-Shilling-Lecture-from-Usa-KR-Dec-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Jeff%20Comer/The-Intimate-Christ-&-the-Pressure-of-the-Consciousness-Jeff-Comer-Usa-KR-Apr-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-Eternal-Femenine-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Apr-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/True-Freedom-Robert-Marino-Lecture-from-Usa-KoradiRadio-May-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/Defending-the-Ramparts-of-the-Inner-Temple-Daniel-Hubicki-Lecture-from-Au-KR-Jul-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/739-Love-is-Law-Valentine-s-Day-Special-Paul-Movsessian-Lecture-Au-KR-Feb-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/677-Taking-Refuge-in-the-Sacred-Heart-of-Christ-Paul-Movsessian-Practice-Au-KR-Dec-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/Gnostic-Kabbala-and-the-Misuse-of-Speech-Part2-David-Serfati-Lecture-Mx-KR-Jan-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/842-Ego-Death-in-22-Steps-David-Serfati-Practice-from-Mexico-KoradiRadio-Apr-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Neal/Dissolving-Doubts-About-Gnosis-Robert-Neal-Lecture-from-Usa-KoradiRadio-Apr-2011.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/The-8-Virtues-of-Kundalini-Thomas-Nilsson-Lecture-from-India-KoradiRadio-Nov-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/The-Tao-of-Gnosis-Thomas-Nilsson-Lecture-from-India-KoradiRadio-Nov-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part16-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Feb-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/Self-Identity-in-the-Gnostic-Teachings-part3-Adolfo-Suero-Lecture-Usa-KR-Mar-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Azzam/Music-of-the-Spheres-Diana-Azzam-Lecture-from-Australia-KoradiRadio-Oct-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Dorismel Díaz/Mysticism-in-the-Spanish-Golden-Age-Dorismel-Diaz-Reflection-from-Canada-KR-Jul-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/The-Awakening-Process-part1-Rafael-Arape-from-Australia-KoradiRadio-Apr-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part8-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Aug-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/762-P-to-Heal-the-M-Body-with-H-Trismegistus-and-Raphael-D-Serfati-Practice-KR-Jul-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/827-Rune-Tyr-Bar-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Mar-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/Existences-&-The-Spiritual-Trajectory-of-VM-SAW-Daniel-Hubicki-Lecture-Au-KR-Sep-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/Practical-Guidelines-For-The-Inner-Work-Thomas-Nilsson-Lecture-from-India-KR-Apr-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/700-The-Mysterious-Path-of-the-Bodhisattva-Carly-Samish-Lecture-from-Usa-KR-May-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/Resolving-the-Seven-Jewels-of-the-Yellow-Dragon-Paul-Movsessian-Lecture-Au-KR-Aug-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Margaret%20Starbird/Mary-Magdalene-Bride-and-Beloved-Interview-with-Margaret-Starbird-KR-Oct-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Tarot-&-Kabalah-part1-Intro-Andrus-Shilling-Lecture-from-Usa-KR-May-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/833-Crime-Part-2-Paul-Movsessian-Lecture-from-Australia-KoradiRadio-Mar-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Benjamin%20Matheson/Father-I-Pray-thee-Teach-me-Wherein-is-Perfect-Joy-Ben-Matheson-Usa-KR-Feb-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/757-Gnostic-Tarot-&-Kabalah-part15-Arcanum-13-Andrus-Shilling-Lecture-Usa-KR-May-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Jesús Gonzalez/Gnostic-Didactic-for-the-Annihilation-of-the-Ego-Jesus-Gonzalez-Practice-Mx-KR-Jan-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2012-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-English-Translation-RM-Dec-2012.zip',
  'http://www.koradiaudio.com/radio_recordings/Carlos%20Guevara/The-Social-Christ-Carlos-Guevara-Lecture-from-Usa-KoradiRadio-Aug-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/Simplicity-Laura-Barge-Lecture-from-Brazil-KoradiRadio-Jun-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/718-Who-is-the-Interior-Man-Marc-Meinharth-Lecture-from-Australia-KoradiRadio-Sep-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Dorismel Díaz/769-Practice-to-Develop-Mysticism-Dorismel-Diaz-Practice-from-Canada-KR-Jul-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/The-Marvelous-Ladder-Daniel-Hubicki-Lecture-from-Australia-KoradiRadio-Dec-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/798-Gnostic-Tarot-&-Kabalah-part16-Arcanum-14-Andrus-Shilling-Lecture-Usa-KR-Nov-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/669-Gnosis-and-the-Current-Human-Condition-Adolfo-Suero-Lecture-from-Usa-KR-Oct-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Jeff%20Comer/Oh-Divine-Mother-Judith-Young-Comer-Lecture-from-Usa-KoradiRadio-May-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/The-Mystery-Religions-of-the-Ancients-part3-Andrus-Shilling-Lecture-Usa-KR-Aug-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/Know-the-Truth-and-the-Truth-will-set-you-Free-Robert-Marino-Lecture-Usa-KR-May-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Carlos%20Guevara/World-Psycho-Politics-and-the-Karma-of-Nations-part1-Carlos-Guevara-Usa-KR-Oct-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Dream-Yoga-and-the-Astral-World-part1-Andrus-Shilling-Lecture-from-Usa-KR-Nov-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Christian%20Vallejo/782-Muladhara-Chakra-Meditation-Christian-Vallejo-Practice-from-Usa-KR-Sep-2020).zip',
  'http://www.koradiaudio.com/radio_recordings/Scott%20Billings/714-Merits-of-the-Heart-Scott-Billings-Lecture-from-Scotland-KoradiRadio-Aug-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part6-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jun-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Carlos%20Guevara/Misterium-Iniquitatis-Carlos-Guevara-Lecture-from-Usa-KoradiRadio-Sep-2011.zip',
  'http://www.koradiaudio.com/radio_recordings/Poorang%20Aurasteh/The-Virtues-of-the-Being-Poorang-Aurasteh-Lecture-from-Usa-KoradiRadio-Aug-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/707-Gnostic-Tarot-&-Kabalah-part10-Arcanum-8-Andrus-Shilling-Lecture-Usa-KR-Jul-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/831-Rune-Ur-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Mar-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/825-Gnostic-Tarot-&-Kabalah-part17-Arcanum-15-Andrus-Shilling-Lecture-Usa-KR-Feb-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/795-Identity-Image-Value-and-the-A-of-C-R-Arape-October-27-Special-KR-Oct-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Carlos%20Guevara/World-Psycho-Politics-and-the-Karma-of-Nations-part2-Carlos-Guevara-Usa-KR-Nov-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Antonio Maldonado Mérida/Interview-2006-with-Antonio-Maldonado-KoradiRadio-Dec-2006.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2009-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-English-Translation-Part1-KR.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/673-The-Path-Constant-Transvaluation-Marc-Meinharth-Lecture-from-Australia-KR-Nov-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part11-Capricorn-Andrus-Shilling-Lecture-from-Usa-KR-Jan-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-Esoteric-Discipline-of-the-Holy-Week-Ana-del-Angel-Lecture-from-Usa-KR-Mar-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Jeff%20Comer/Gnosis-Inspiration-and-the-Path-of-Love-Judith-Young-Lecture-from-Usa-KR-Feb-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/Fantasy-and-Reality-Robert-Marino-Lecture-from-Usa-KoradiRadio-Dec-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/770-Relaxation-Transforming-Daily-Impressions-Mira-Meintharth-Practice-Au-KR-Aug-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/777-Prajnaparamita-Meditation-David-Serfati-Practice-from-Mexico-KoradiRadio-Aug-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part12-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Oct-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Carlos%20Guevara/The-Consciousness-and-the-Emotional-Center-Carlos-Guevara-Lecture-Usa-KR-Jan-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part3-Andrus-Shilling-Lecture-from-Usa-KR-Oct-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/789-Rune-Ar-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Oct-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part13-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Dec-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part12-Andrus-Shilling-Lecture-from-Usa-KR-Oct-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/The-Four-Elements-in-Nature-and-the-Esoteric-Work-Carly-Samish-Lecture-Usa-KR-Sep-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/774-Rune-Fa-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Aug-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/776-Happiness-Through-Superior-Meditation-Ana-del-Angel-Lecture-from-Usa-KR-Aug-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/The-Gnostic-Tibet-Thomas-Nilsson-Lecture-from-Sweden-KoradiRadio-Nov-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/687-Gnostic-Tarot-&-Kabalah-part7-Arcanum-5-Andrus-Shilling-Lecture-Usa-KR-Feb-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/A-Century-with-the-VM-SAW-1917-2017-Rafael-Vargas-Lecture-from-Italy-KR-Mar-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Jeff%20Comer/Life-Lived-Intensely-with-Love-and-Rectitude-Jeff-Comer-Lecture-from-Usa-KR-Oct-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/741-Gnostic-Tarot-&-Kabalah-part13-Arcanum-11-Andrus-Shilling-Lecture-Usa-KR-Feb-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/Meditation-and-Psychological-Death-Adolfo-Suero-Lecture-from-Usa-KR-Nov-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/Self-Remembering-Marc-Meinharth-Lecture-from-Australia-KoradiRadio-May-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Trent McHugh/834-Om-Mani-Padme-Hum-Melanie-McHugh-Practice-from-Australia-KR-Mar-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/Freeing-the-Consciousness-from-its-Conditioning-Factors-part2-R-Arape-Au-KR-Mar-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Jesús Gonzalez/Cosmic-Consciousness-Jesus-Gonzalez-Lecture-from-Mexico-KoradiRadio-Nov-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/679-The-Esoteric-Symbolism-of-Christmas-Robert-Marino-Lecture-from-Usa-KR-Dec-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Azzam/Saint-Valentine-s-Day-Diana-Azzam-Lecture-from-Australia-KoradiRadio-Feb-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Robert%20Marino/The-Truth-About-UFOs-Robert-Marino-Lecture-from-USA-KoradiRadio-Jan-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/Hercolubus-The-Planet-X-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Jul-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part2-Aries-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jun-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part9-Andrus-Shilling-Lecture-from-Usa-KR-Apr-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Trent McHugh/Fire-and-Light-Consciousness-and-Intuition-Trent-McHugh-Lecture-from-Au-KR-Feb-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part1-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jan-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/815-Jeu-The-Great-Enlightener-David-Serfati-Practice-from-Mexico-KoradiRadio-Jan-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/819-Rune-Sig-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Jan-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/797-Simple-R-and-Awareness-Strengthening-P-Marc-Meintharh-Practice-Au-KR-Nov-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part5-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-May-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part1-Andrus-Shilling-Lecture-from-Usa-KR-Aug-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part4-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Apr-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part1-Introduction-Andrus-Shilling-Lecture-from-Usa-KR -Jun-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-Crystallization-of-the-Soul-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Jan-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/The-Process-of-Cristification-Adolfo-Suero-Lecture-from-USA-KoradiRadio-Jan-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Davin%20Thomas/The-Psychology-of-the-Tarot-part3-Davin-Thomas-Lecture-from-Usa-KR-Jul-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Cipolletta/858-Karma-and-How-to-Trans-Pain-into-Spiritual-Practice-Diana-Cipolletta-Spain-KR-Jul-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Helen%20Sjolund/Exploring-Forgiveness-Helen-Sjolund-Lecture-from-Canada-KoradiRadio-Mar-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2014-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-from-Spain-KR-Feb-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/Watchfulness-is-a-Fire-in-the-Heart-Carly-Samish-Lecture-from-Usa-KoradiRadio-Jul-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/Egypt-Lifting-the-Viel-of-Isis-Thomas-Nilsson-Lecture-from-Sweden-KoradiRadio-May-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/716-Gnostic-Tarot-&-Kabalah-part11-Arcanum-9-Andrus-Shilling-Lecture-Usa-KR-Sep-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/The-Art-of-Being-Laura-Barge-Lecture-from-Brazil-KoradiRadio-Feb-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/The-Astral-Light-Paul-Movsessian-Lecture-from-Australia-KoradiRadio-Nov-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Scott%20Billings/837-Inri-the-Perfect-Multiple-Unity-Holy-Week-Special-Scott-Billings-Scotland-KR-Apr-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part12-Aquarius-Andrus-Shilling-Lecture-from-Usa-KR-Jan-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Patricia Gallagher/838-The-Falling-Away-of-the-Bodies-Patricia-Gallagher-Practice-from-Usa-KR-Apr-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part14-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Dec-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/Self-Identity-in-the-Gnostic-Teachings-part1-Adolfo-Suero-Lecture-Usa-KR-Sep-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part11-Andrus-Shilling-Lecture-from-Usa-KR-Sep-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Javier Casañ/Gnosis-the-Search-for-the-Lost-Love-Javier-Casan-Lecture-from-Spain-KR-Sep-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/The-Awakening-of-Consciousness-part-3-Rafael-Arape-Lecture-from-Au-KR-Nov-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-Cosmic-Christ-and-the-Holy-Week-Ana-del-Angel-Lecture-from-Usa-KR-March-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/Love-and-Transmutation-Carly-Samish-Lecture-from-Usa-KoradiRadio-Aug-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/The-Perfect-Matrimony-and-the-Christ-Jennifer-Hubicki-Lecture-from-Australia-KR-Dec-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/The-Three-Gunas-and-Creation-Paul-Movsessian-Lecture-from-Australia-KR-Oct-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/735-The-Hermetic-Seal-and-The-7-Radicals-of-Fire-Thomas-Nilsson-from-India-KR-Jan-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/Marriage-&-Love-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Feb-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part5-Andrus-Shilling-Lecture-from-Usa-KR-Dec-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Last-Supper-Rafael-Vargas-Lecture-from-Italy-Easter-Special-KoradiRadio-Mar-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/874-The-Living-Scripture-of-Nature-Carly-Herrero-Lecture-from-Usa-KoradiRadio-Oct-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part4-Andrus-Shilling-Lecture-from-Usa-KR-Nov-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Patrick%20Donovan/Living-Within-the-Four-Pillars-Patrick-Donovan-Lecture-from-Usa-KoradiRadio-Jun-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/The-Mystery-Religions-of-the-Ancients-part1-Andrus-Shilling-Lecture-Usa-KR-Jun-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part11-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Sep-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Justin%20Short/Gnostic-Meditation-Part4-Justin-&-Lynn-Short-Lecture-from-Usa-KoradiRadio-Mar-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Davin%20Thomas/The-Psychology-of-the-Tarot-part2-Davin-Thomas-Lecture-from-Usa-KR-May-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2011-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-English-Translation-RM.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/Holy-Week-Cause-Effect-and-Consequence-Rafael-Vargas-Lecture-from-It-KR-Mar-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Scott%20Billings/Intimate-Psychoanalisis-and-the-Dissolution-of-the-Ego-Scott-Billings-UK-KR-Sep-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Tarot-&-Kabalah-part4-Arcanum-2-Andrus-Shilling-Lecture-from-Usa-KR-Aug-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Laura%20Alvarez/689-Sahaja-Maithuna-Laura-&-Marco-Albarez-Practice-from-Usa-Feb-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/Gnostic-Revelations-of-the Mayab-Thomas-Nilsson-Lecture-from-Sweden-KR-Feb-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part2-Andrus-Shilling-Lecture-from-Usa-KR-Sep-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/712-Reflections-About-Thelema-Thomas-Nilsson-Lecture-from-India-KR-Aug-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Scott%20Billings/Will-a-Value-of-the-Being-Scott-Billing-Lecture-from-UK-KoradiRadio-Aug-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Carl%20Penk/The-Search-For-Fulfillment-Carl-Penk-Lecture-From-Au-KR-April-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Davin%20Thomas/Cosmic-Influence-and-The-Three-Forces-Davin-Thomas-Lecture-from-Usa-KR-Nov-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/Beauty-and-the-World-of-Tiphereth-Paul-Movsessian-Lecture-from-Australia-KR-Jul-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Azzam/Mysticism-Music-and-Movement-Diana-Azzam-Lecture-from-Australia-KoradiRadio-Oct-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Astral-Experience-and-the-Death-of-the-Ego-part2-Rafael-Vargas-Italy-KR-Jun-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/702-Alchemy-Adolfo-Suero-Lecture-from-Usa-KoradiRadio-Jun-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part18- Andrus-Shilling-Lecture-from-Usa-KoradiRadio-May-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/764-Love-and-Death-Marc-Meinharth-Lecture-from-Australia-KoradiRadio-Jul-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Jeff%20Comer/Love-and-Sacrifice-Jeff-Comer-Lecture-From-Usa-KoradiRadio-Jul-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part10-Andrus-Shilling-Lecture-from-Usa-KR-May-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/Rumi-Herart-&-Soul-Carly-Samish-Lecture-from-Usa-KoradiRadio-Mar-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part13-Pisces-Andrus-Shilling-Lecture-from-Usa-KR-Feb-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2015-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-English-Translation-RM-Dec-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Christian%20Vallejo/785-Svadhisthana-Chakra-Meditation-Christian-Vallejo-Practice-from-Usa-KR-Sep-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/The-Astrological-Ages-and-the-New-Era-of-Aquarius-Carly-Samish-Lecture-Usa-KR-Nov-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/The-Awakening-of-Consciousness-part-2-Rafael-Arape-Lecture-from-Au-KR-Aug-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-Great-Law-of-Karma-and-Dharma-Ana-del-Angel-Lecture-from-Usa-KR-Jul-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael Arapé/The-Awakening-Process-part2-Rafael-Arape-from-Australia-KoradiRadio-Aug-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/796-The-Lords-Prayer-Our-Father-Mira-Meintharth-Practice-from-Australia-KR-Nov-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part20-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jul-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Dorismel Díaz/681-R-on-Gnostic-Prophecies-in-the-Age-of-Aquarius-Dorismel-Diaz-Lecture-Ca-KR-Dec-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Gnostic-Mystery-of-Christmas-Rafael-Vargas-Holiday-Special-KoradiRadio-Dec-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/Gnostic-Anthropology-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Mar-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part2-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Feb-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/The-Awakening-of-the-Consciousness-Daniel-Hubicki-Lectures-from-Au-KR-Apr-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part8-Andrus-Shilling-Lecture-from-Usa-KR-Apr-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Javier Casañ/Gnosis-21st-Century-Javier-Casan-Lecture-from-Spain-KoradiRadio-Jul-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Helen Sjolund/Trees-of-Creation-Helen-Sjolund-Lecture-from-Canada-KoradiRadio-Nov-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Dorismel Díaz/Gnostic-Approach-to-Knight-Hood-Tales-Dorismel-Diaz-Lecture-from-Canada-KR-Jun-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/747-Gnostic-Tarot-&-Kabalah-part14-Arcanum-12-Andrus-Shilling-Lecture-Usa-KR-Mar-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/Self-Identity-in-the-Gnostic-Teachings-part2-Adolfo-Suero-Lecture-Usa-KR-Jan-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part10-Sagittarius-Andrus-Shilling-Lecture-from-Usa-KR-Dec-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/Parameters-of-Sexual-Continence-David-Serfati-Lecture-from-Mexico-KR-Feb-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/Revolutionary-Psychology-The-Beloved-Ego-Ana-del-Angel-Lecture-from-Usa-KR-Aug-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Helen%20Sjolund/Exploring-Willpower-Helen-Sjound-Lecture-from-Canada-KoradiRadio-Jun-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Adolfo%20Suero/848-The-White-Lodge-and-the-G-M-Adolfo-Suero-New-Zealand-KR-May-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/The-Mystery-Religions-of-the-Ancients-part4-Andrus-Shilling-Lecture-Usa-KR-Sep-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Astrology-Part6-Leo-Andrus-Shilling-Lecture-from-Usa-KR-Aug-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Rene%20Barge/Gnosis-is-Lived-in-Deeds-Rene-Barge-Lecture-from-Usa-KoradiRadio-May-2011.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Dream-Yoga-and-the-Astral-World-part2-Andrus-Shilling-Lecture-from-Usa-KR-Dec-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/826-Meditation-on-Dying-Paul-Movsessian-Practice-from-Australia-KoradiRadio-Feb-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/845-Gnostic-Tarot-&-Kabalah-part18-Arcanum-16-Andrus-Shilling-Lecture-Usa-KR-May-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/683-Gnostic-Tarot-&-Kabalah-part6-Arcanum-4-Andrus-Shilling-Lecture-Usa-KR-Jan-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Azzam/Reflections-on-the-Motivation-of-our-Inner-Work-Diana-Azzam-Lecture-from-Au-KR-Jun-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Justin%20Short/Gnostic-Meditation-Part2-Justin-&-Lynn-Short-Lecture-from-Usa-KoradiRadio-Jan-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Astral-Experience-and-the-Death-of-the-Ego-part1-Rafael-Vargas-Italy-KR-May-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/822-Attacks-of-B-M-Prevention-and-Psychic-Defense-P2-David-Serfati-Mx-KR-Feb-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/761-The-Science-of-Meditation-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Jun-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Thomas%20Nilsson/727-The-4-Noble-Truths-of-Buddha-in-the-Light-of-Gnosis-Thomas-Nilsson-India-KR-Nov-2019.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part14-Andrus-Shilling-Lecture-from-Usa-KR-Apr-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Marc%20Meinharth/Human-Problems-&-Faith-Marc-Meinharth-Lecture-from-Australia-KR-Apr-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Rafael%20Vargas/The-Astral-Experience-and-the-Death-of-the-Ego-part3-Rafael-Vargas-Italy-KR-Sep-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Oscar%20Uzcategui/Interview-2009-with-Mr-Oscar-Uzcategui-VM-Kwen-Khan-English-Translation-Part2-KR.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part7-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jul-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Paul%20Movsessian/Guru-Yoga-Paul-Movsessian-Lecture-from-Australia-KoradiRadio-Jun-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/David%20Serfati/Gnostic-Kabbala-and-the-Misuse-of-Speech-Part1-David-Serfati-Lecture-Mx-KR-Dec-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Tarot-&-Kabalah-part2-Intro-Andrus-Shilling-Lecture-from-Usa-KR-Jun-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Carly%20Samish/811-The-Dissolution-of-the-Body-at-Death-Carly-Samish-Practice-from-Usa-KR-Jan-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Daniel%20Hubicki/Vision-and-Action-Daniel-Hubicki-Lecture-from-Australia-KoradiRadio-Sep-2013.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Tarot-&-Kabalah-part3-Arcanum-1-Andrus-Shilling-Lecture-from-Usa-KR-Jul-2018.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/765-Meditation-with-O-vowel-Andrus-Shilling-Practice-from-Usa-KoradiRadio-Jul-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Justin%20Short/Gnostic-Meditation-Part3-Justin-&-Lynn-Short-Lecture-from-Usa-KoradiRadio-Feb-2015.zip',
  'http://www.koradiaudio.com/radio_recordings/Diana%20Cipolletta/869-How-to-Understand-Fear-and-Overcome-it-Diana-Cipolletta-L-from-Spain-KR-Sep-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Sam%20Semir%20Osmanagich/The-Bosnian-Valley-of-the-Pyramids-Interview-with-Dr-Sam-Semir-Osmanagich-KR-Jul-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Justin%20Short/Gnostic-Meditation-Part1-Justin-&-Lynn-Short-Lecture-from-Usa-KoradiRadio-Dec-2014.zip',
  'http://www.koradiaudio.com/radio_recordings/Jeff%20Comer/The-Psychological-World-of-the-Chakras-Judith-Young-Comer-Lecture-from-Usa-KR-Jul-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/The-Miracle-of-Love-Ana-del-Angel-Lecture-from-Usa-KoradiRadio-Feb-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/781-Rune-Is-Ana-del-Angel-Practice-from-Usa-KoradiRadio-Sep-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Chemistry-&-Cosmology-part7-Andrus-Shilling-Lecture-from-Usa-KR-Mar-2017.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/814-Gnostic-Parenthood-Part-3-Infant-s-Self-Cognizance-Ana-del-Angel-Usa-KR-Jan-2021.zip',
  'http://www.koradiaudio.com/radio_recordings/Ana%20del%20Angel/805-Gnostic-Parenthood-Part-2-Maternity-Ana-del-Angel-Lecture-from-Usa-KR-Dec-2020.zip',
  'http://www.koradiaudio.com/radio_recordings/Benjamin%20Matheson/Prayer-in-the-Work-Ben-Matheson-Lecture-from-Usa-KoradiRadio-Mar-2016.zip',
  'http://www.koradiaudio.com/radio_recordings/Andrus%20Shilling/Gnostic-Psychology-part15-Andrus-Shilling-Lecture-from-Usa-KoradiRadio-Jan-2016.zip'
];
